name: ci

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.6'
          cache-dependency-path: go.sum

      - name: Go Version
        run: go version

      - name: Go Test
        run: go test ./...
